import type { PromptCodeRule } from "./types";

export const PROMPT_CODE_RULES: PromptCodeRule[] = [
  {
    id: "javascript.llm.security.prompt-injection.openai-unsafe-template",
    severity: "ERROR",
    category: "prompt-injection",
    message:
      "User input in OpenAI prompt via template literal. Sanitize user input before including in prompts.",
    pattern:
      /(?:openai\.chat\.completions\.create|client\.chat\.completions\.create)\s*\([^)]*`[^`]*\$\{/g,
    fileTypes: [".js", ".jsx", ".ts", ".tsx"],
    confidence: "HIGH",
    tier: "likely-exploitable",
    requiresUntrustedInput: true,
    action: "WARN",
  },
  {
    id: "javascript.llm.security.prompt-injection.openai-unsafe-concat",
    severity: "ERROR",
    category: "prompt-injection",
    message: "User input concatenated into OpenAI prompt. Use input sanitization.",
    pattern:
      /(?:openai\.|client\.chat\.completions\.create)[\s\S]{0,200}?content\s*:\s*[^,}\n]+\+/g,
    fileTypes: [".js", ".jsx", ".ts", ".tsx"],
    confidence: "HIGH",
    tier: "likely-exploitable",
    requiresUntrustedInput: true,
    action: "WARN",
  },
  {
    id: "javascript.llm.security.prompt-injection.anthropic-unsafe",
    severity: "ERROR",
    category: "prompt-injection",
    message: "User input in Anthropic prompt without sanitization. Validate and sanitize before API call.",
    pattern:
      /(?:anthropic\.messages\.create|client\.messages\.create|new\s+Anthropic)[\s\S]{0,200}?`[^`]*\$\{/g,
    fileTypes: [".js", ".jsx", ".ts", ".tsx"],
    confidence: "HIGH",
    tier: "likely-exploitable",
    requiresUntrustedInput: true,
    action: "WARN",
  },
  {
    id: "typescript.llm.security.prompt-injection.ai-sdk-unsafe-template",
    severity: "ERROR",
    category: "prompt-injection",
    message:
      "Untrusted data interpolated into Vercel AI SDK prompt. Keep system instructions fixed and validate user content.",
    pattern: /(?:generateText|streamText)\s*\(\s*\{[\s\S]{0,300}?(?:prompt|messages)[\s\S]{0,120}?`[^`]*\$\{/g,
    fileTypes: [".js", ".jsx", ".ts", ".tsx"],
    confidence: "HIGH",
    tier: "likely-exploitable",
    requiresUntrustedInput: true,
    action: "WARN",
  },
  {
    id: "javascript.llm.security.prompt-injection.langchain-unsafe",
    severity: "ERROR",
    category: "prompt-injection",
    message: "LangChain prompt template includes unsanitized interpolation. Validate template variables.",
    pattern:
      /(?:PromptTemplate\.fromTemplate|ChatPromptTemplate\.fromMessages)\s*\([\s\S]{0,200}?`[^`]*\$\{/g,
    fileTypes: [".js", ".jsx", ".ts", ".tsx"],
    confidence: "HIGH",
    tier: "suspicious-construction",
    requiresUntrustedInput: true,
    action: "WARN",
  },
  {
    id: "javascript.llm.security.output-injection.eval-llm-response",
    severity: "ERROR",
    category: "prompt-injection-output",
    message: "eval() on LLM response. Never execute LLM outputs directly.",
    pattern: /eval\s*\(\s*(?:response|completion|output|result|text|message)/g,
    fileTypes: [".js", ".jsx", ".ts", ".tsx"],
    confidence: "HIGH",
    tier: "likely-exploitable",
    action: "BLOCK",
  },
  {
    id: "javascript.llm.security.output-injection.function-constructor",
    severity: "ERROR",
    category: "prompt-injection-output",
    message: "new Function() with LLM response. This is equivalent to eval().",
    pattern: /new\s+Function\s*\(\s*(?:response|completion|output|result|text|message)/g,
    fileTypes: [".js", ".jsx", ".ts", ".tsx"],
    confidence: "HIGH",
    tier: "likely-exploitable",
    action: "BLOCK",
  },
  {
    id: "python.llm.security.prompt-injection.openai-unsafe-fstring",
    severity: "ERROR",
    category: "prompt-injection",
    message: "User input directly interpolated into OpenAI prompt via f-string.",
    pattern: /(?:client\.chat\.completions\.create|openai\.ChatCompletion\.create)[\s\S]{0,200}?f["']/g,
    fileTypes: [".py"],
    confidence: "HIGH",
    tier: "likely-exploitable",
    requiresUntrustedInput: true,
    action: "WARN",
  },
  {
    id: "python.llm.security.prompt-injection.openai-unsafe-concat",
    severity: "ERROR",
    category: "prompt-injection",
    message: "User input concatenated into OpenAI prompt.",
    pattern: /(?:client\.chat\.completions\.create|openai\.ChatCompletion\.create)[\s\S]{0,200}?\+/g,
    fileTypes: [".py"],
    confidence: "HIGH",
    tier: "likely-exploitable",
    requiresUntrustedInput: true,
    action: "WARN",
  },
  {
    id: "python.llm.security.prompt-injection.anthropic-unsafe-fstring",
    severity: "ERROR",
    category: "prompt-injection",
    message: "User input directly interpolated into Anthropic prompt via f-string.",
    pattern: /(?:anthropic\.messages\.create|client\.messages\.create)[\s\S]{0,200}?f["']/g,
    fileTypes: [".py"],
    confidence: "HIGH",
    tier: "likely-exploitable",
    requiresUntrustedInput: true,
    action: "WARN",
  },
  {
    id: "python.llm.security.output-injection.eval-llm-response",
    severity: "ERROR",
    category: "prompt-injection-output",
    message: "eval() on LLM response. Never execute LLM-generated code directly.",
    pattern: /eval\s*\(\s*(?:response|completion|output|message|text)/g,
    fileTypes: [".py"],
    confidence: "HIGH",
    tier: "likely-exploitable",
    action: "BLOCK",
  },
];
