import "server-only";

import { randomUUID } from "node:crypto";
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import type {
  EngineApplicabilityInput,
  EngineApplicabilityResult,
  EngineExecuteInput,
  EngineHealthCheckResult,
  EngineResult,
  SecurityEngine,
} from "../types";
import { safeExec, withIsolatedWorkspace } from "../subprocess/safe-exec";
import { fromOpenGrepMatch, type OpenGrepMatch } from "./normalize";

/**
 * Phase 35, section 5/6: verified against the real, currently-published
 * opengrep/opengrep GitHub release as of this phase (repository:
 * https://github.com/opengrep/opengrep, tag v1.30.0, published 2026-09-07,
 * LICENSE = GNU LGPL-2.1). Pinned explicitly -- never "latest".
 *
 * Verified CLI contract by real execution against real fixtures (not just
 * `--help` text): `opengrep-core -json -lang <lang> -rules <file> <single
 * target file>` is the only reliably-scriptable invocation this binary
 * supports without depending on opengrep-core's undocumented internal
 * `-targets` JSON schema (a polymorphic-variant ATD format meant to be
 * generated by the higher-level Python `opengrep` wrapper, not hand-built --
 * confirmed by testing plain-text and naive-JSON target-list files against a
 * real binary, both rejected with a parser error naming the internal
 * `Semgrep_output_v1_j.read_target` type). This engine therefore invokes the
 * binary once per applicable file. See Phase 35 final report, section 7, for
 * the full verification transcript.
 */
export const OPENGREP_VERSION = "1.30.0";
export const OPENGREP_LICENSE = "LGPL-2.1";
export const OPENGREP_REPOSITORY = "https://github.com/opengrep/opengrep";

// Phase 42: the Security Worker bundles this file (and everything else)
// into a SINGLE esbuild-produced CJS file at /app/worker-bundle.cjs. At
// runtime, __dirname inside that bundle is the bundle's OWN directory
// (/app), not this source file's original directory -- so
// join(__dirname, "rules", ...) silently resolved to the non-existent
// /app/rules/taint-rules.yaml in the deployed worker (the Dockerfile
// copies the real rules file to /app/server/security-engines/opengrep/rules/
// instead, its source-relative path, since that's what it can see at build
// time). Every single opengrep-core invocation therefore passed a
// nonexistent -rules path, which crashed with an unhandled OCaml exception
// (exit 2, "unknown exception ... Parse_rule.parse_file") on every file,
// 100% of the time -- found via Phase 41's real E2E test, root-caused via
// real Railway container access in Phase 42 (confirmed live: /app/rules/
// does not exist; only /app/server/security-engines/opengrep/rules/ does).
// This never reproduced locally or in unbundled test runs, where __dirname
// correctly points at this file's real directory -- only the bundled
// worker was ever affected.
//
// Fix: same pattern already used for OPENGREP_BINARY_PATH/TRIVY_BINARY_PATH
// -- an explicit, deployment-configurable override, defaulting to the
// __dirname-relative path for local/Vercel/test runs (where it has always
// been correct). worker/Dockerfile sets OPENGREP_RULES_PATH to the exact
// path it actually copies the file to.
const RULES_FILE = process.env.OPENGREP_RULES_PATH?.trim() || join(__dirname, "rules", "taint-rules.yaml");
const DEFAULT_PER_FILE_TIMEOUT_MS = 15_000;
const MAX_FILES_PER_EXECUTION = 60;
const MAX_TARGET_FILE_BYTES = 1_000_000;

const LANGUAGE_BY_EXTENSION: Record<string, string> = {
  ".js": "javascript",
  ".jsx": "javascript",
  ".mjs": "javascript",
  ".cjs": "javascript",
  ".ts": "typescript",
  ".tsx": "typescript",
  ".py": "python",
};

function resolveBinaryPath(): string | null {
  return process.env.OPENGREP_BINARY_PATH?.trim() || null;
}

function detectLanguage(path: string): string | null {
  const ext = path.slice(path.lastIndexOf(".")).toLowerCase();
  return LANGUAGE_BY_EXTENSION[ext] ?? null;
}

type RawOpenGrepJson = {
  results?: OpenGrepMatch[];
  errors?: Array<{ message?: string }>;
};

/**
 * opengrep-core can emit a stray leading byte (observed: a single "."
 * progress-indicator character) before the JSON object on stdout in some
 * versions -- confirmed by hexdumping real output during verification.
 * Defensive: always locate the first '{' rather than assuming byte 0.
 */
function parseOpenGrepJson(stdout: string): RawOpenGrepJson | null {
  const start = stdout.indexOf("{");
  if (start === -1) return null;
  try {
    return JSON.parse(stdout.slice(start)) as RawOpenGrepJson;
  } catch {
    return null;
  }
}

async function runOnSingleFile(
  binary: string,
  workspaceDir: string,
  originalPath: string,
  content: string,
  language: string,
  timeoutMs: number
): Promise<{ matches: OpenGrepMatch[]; errorMessage: string | null }> {
  const safeName = `${randomUUID()}${originalPath.slice(originalPath.lastIndexOf("."))}`;
  const targetPath = join(workspaceDir, safeName);
  await writeFile(targetPath, content, "utf8");

  const result = await safeExec({
    command: binary,
    args: ["-json", "-lang", language, "-rules", RULES_FILE, "-max_memory", "1024", "-timeout", "10", targetPath],
    cwd: workspaceDir,
    timeoutMs,
  });

  if (result.timedOut) {
    return { matches: [], errorMessage: "per-file timeout exceeded" };
  }
  if (result.exitCode !== 0 && result.exitCode !== 1) {
    // opengrep-core's own convention: 0 = clean run, 1 = clean run with
    // findings for some invocations depending on version; anything else is
    // a real execution failure, not "no findings." Phase 42: exit 2
    // specifically means opengrep-core's own "unknown exception" (a fatal,
    // unhandled exception in its OCaml core -- confirmed by real
    // invocation, never "vulnerability found" and never a memory-limit hit,
    // which the binary reports separately as an exit-0 warning). stderr
    // used to be discarded entirely here, which made a real Phase 41/42
    // production failure (opengrep-core exited 2 on ~60 files, never
    // reproduced against the same binary/container/files/rules on retest --
    // most consistent with a transient cold-start condition) undiagnosable
    // after the fact. Always capture a bounded stderr excerpt now.
    const stderrExcerpt = result.stderr.trim().slice(-500);
    return {
      matches: [],
      errorMessage: `opengrep-core exited ${result.exitCode}${stderrExcerpt ? `: ${stderrExcerpt}` : ""}`,
    };
  }

  const parsed = parseOpenGrepJson(result.stdout);
  if (!parsed) {
    return { matches: [], errorMessage: "could not parse opengrep-core JSON output" };
  }

  // Re-point the reported path back at the caller's original repository-
  // relative path -- the on-disk target file is a randomized, workspace-local
  // name that must never leak into findings.
  const matches = (parsed.results ?? []).map((m) => ({ ...m, path: originalPath }));
  return { matches, errorMessage: null };
}

export function createOpenGrepEngine(): SecurityEngine {
  return {
    id: "opengrep",
    name: "OpenGrep",
    version: OPENGREP_VERSION,
    capabilities: [
      { id: "ast", engine: "opengrep", expensive: true, networkRequired: false, requiresExternalBinary: true },
      { id: "taint", engine: "opengrep", expensive: true, networkRequired: false, requiresExternalBinary: true },
      { id: "dataflow", engine: "opengrep", expensive: true, networkRequired: false, requiresExternalBinary: true },
      { id: "semantic", engine: "opengrep", expensive: true, networkRequired: false, requiresExternalBinary: true },
    ],

    applicability(input: EngineApplicabilityInput): EngineApplicabilityResult {
      const applicableFiles = input.files.filter((f) => detectLanguage(f.path) != null);
      if (applicableFiles.length === 0) {
        return { applicable: false, reason: "no JS/TS/Python source files found", matchedCapabilities: [] };
      }
      return {
        applicable: true,
        reason: `${applicableFiles.length} JS/TS/Python file(s) found`,
        matchedCapabilities: ["ast", "taint", "dataflow", "semantic"],
      };
    },

    async healthCheck(): Promise<EngineHealthCheckResult> {
      const binary = resolveBinaryPath();
      if (!binary) {
        return { healthy: false, reason: "OPENGREP_BINARY_PATH is not configured" };
      }
      const result = await safeExec({ command: binary, args: ["-version"], cwd: "/tmp", timeoutMs: 5_000 });
      if (result.exitCode !== 0) {
        return { healthy: false, reason: `opengrep-core -version exited ${result.exitCode}` };
      }
      const versionMatch = result.stdout.match(/([\d.]+)/);
      return { healthy: true, reason: "opengrep-core responded to -version", detectedVersion: versionMatch?.[1] };
    },

    async execute(input: EngineExecuteInput): Promise<EngineResult> {
      const executionId = randomUUID();
      const startedAt = new Date().toISOString();
      const started = Date.now();
      const binary = resolveBinaryPath();

      const base = {
        engine: "opengrep" as const,
        engineVersion: OPENGREP_VERSION,
        executionId,
        scanId: input.scanId,
        projectId: input.projectId,
        organizationId: input.organizationId,
        startedAt,
        capabilitiesAttempted: ["ast", "taint", "dataflow", "semantic"] as EngineResult["capabilitiesAttempted"],
      };

      if (!binary) {
        return {
          ...base,
          status: "SKIPPED",
          completedAt: new Date().toISOString(),
          durationMs: Date.now() - started,
          capabilitiesCompleted: [],
          findings: [],
          evidence: [],
          metrics: {},
          errors: [{ code: "not_configured", message: "OPENGREP_BINARY_PATH is not set for this environment" }],
        };
      }

      const targets = input.files
        .map((f) => ({ ...f, language: detectLanguage(f.path) }))
        .filter((f): f is typeof f & { language: string } => f.language != null && f.content.length <= MAX_TARGET_FILE_BYTES)
        .slice(0, MAX_FILES_PER_EXECUTION);

      const allMatches: OpenGrepMatch[] = [];
      const errors: EngineResult["errors"] = [];
      let filesScanned = 0;

      try {
        await withIsolatedWorkspace("opengrep-scan", async (workspaceDir) => {
          for (const target of targets) {
            const perFileTimeout = Math.min(DEFAULT_PER_FILE_TIMEOUT_MS, input.timeoutMs);
            let outcome = await runOnSingleFile(
              binary,
              workspaceDir,
              target.path,
              target.content,
              target.language,
              perFileTimeout
            );
            // Phase 42: a real production run saw ~60/60 files fail with
            // "opengrep-core exited 2" (a fatal unhandled exception inside
            // the OCaml core), which never reproduced on retest against the
            // identical binary/container/rules/files -- most consistent
            // with a transient condition (e.g. a cold container). A single
            // bounded retry recovers from exactly that class of failure
            // without ever turning a REAL, reproducible failure into a
            // false "clean" result: a file that fails twice is still
            // recorded as failed, with both attempts' detail preserved.
            if (outcome.errorMessage?.startsWith("opengrep-core exited")) {
              const retry = await runOnSingleFile(
                binary,
                workspaceDir,
                target.path,
                target.content,
                target.language,
                perFileTimeout
              );
              if (retry.errorMessage) {
                outcome = { matches: retry.matches, errorMessage: `${outcome.errorMessage} (retry also failed: ${retry.errorMessage})` };
              } else {
                outcome = retry;
              }
            }
            const { matches, errorMessage } = outcome;
            filesScanned += 1;
            allMatches.push(...matches);
            if (errorMessage) {
              errors.push({ code: "file_scan_failed", message: `${target.path}: ${errorMessage}` });
            }
          }
        });
      } catch (error) {
        errors.push({ code: "workspace_error", message: error instanceof Error ? error.message : String(error) });
      }

      const { findings, evidence } = fromOpenGrepMatch(allMatches, {
        scanId: input.scanId,
        projectId: input.projectId,
        organizationId: input.organizationId,
      });

      const failedAll = filesScanned > 0 && errors.length >= filesScanned;
      const status = failedAll ? "FAILED" : errors.length > 0 ? "PARTIAL" : "COMPLETED";

      return {
        ...base,
        status,
        completedAt: new Date().toISOString(),
        durationMs: Date.now() - started,
        capabilitiesCompleted: status === "FAILED" ? [] : ["ast", "taint", "dataflow", "semantic"],
        findings,
        evidence,
        metrics: { filesScanned, matchesFound: allMatches.length },
        errors,
      };
    },
  };
}
